name: CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          import-module PowershellGet -Force
          Invoke-WebRequest https://nuget.org/nuget.exe -OutFile '.\AppData\Local\Microsoft\Windows\PowerShell\PowerShellGet\nuget.exe'
          
      - name: Publish Module
        run: |
          Publish-Module -Path $GITHUB_WORKSPACE\Modules\MyModestModule -NuGetApiKey ${{ secrets.psapikey }}
